Repository BDD-CLUB/01-doo-re-front, pull requests merged in 2024-12, with the labels that each got.

#362 Feature/#360 학습자료 수정 시 파일 유형 및 추가 UI 제거
  src/containers/study/CreateDocumentModal/index.tsx
Labels: :art: 디자인

#366 Feature/#364 학습자료스터디 갤러리 권환
  src/app/api/study.ts
  src/app/team/[teamId]/document/page.tsx
  src/app/team/[teamId]/study-gallery/page.tsx
  src/app/team/[teamId]/study/[studyId]/document/page.tsx
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/components/Sidebar/SidebarContent/index.tsx
  src/hooks/useGetMyTeam.ts
Labels: ✨ 기능 개발

#367 Feature/#365 스터디페이지에 학습자료 추가 버튼 구현
  src/app/team/[teamId]/study/[studyId]/page.tsx
Labels: ✨ 기능 개발

#368 Feature/#358 팀과스터디 UI 수정
  src/components/Title/index.tsx
Labels: :lady_beetle: 버그

#363 Feature/#361 학습자료 생성 시 링크는 1개만 첨부할 수 있도록 수정
  src/containers/study/CreateDocumentModal/index.tsx
Labels: :lady_beetle: 버그
