Repository BDD-CLUB/01-doo-re-front, pull requests merged in 2024-07, with the labels that each got.

#275 bug : get 제외 json 파싱 못하도록 수정
  src/app/api/fetcher.ts
Labels: :lady_beetle: 버그

#277 Fix/Login Bug Fix
  src/app/api/fetcher.ts
Labels: :lady_beetle: 버그

#278 Feature/#272 팀 crud 토큰 연결
  src/app/api/team.ts
  src/app/team/[teamId]/page.tsx
  src/components/Title/index.tsx
  src/constants/s3Url.ts
  src/containers/team/DeleteTeamModal/index.tsx
  src/containers/team/TeamModal/index.tsx
  src/mocks/teamInfo.ts
  src/types.ts
Labels: 📬 API, ✨ 기능 개발

#276 Feature/#266 팀원 목록 조회 api 연결
  src/app/api/team.ts
  src/containers/team/teamMember/FiredMemberModal/index.tsx
  src/containers/team/teamMember/MandateMemberModal/index.tsx
  src/containers/team/teamMember/index.tsx
  src/containers/team/teamMember/types.ts
Labels: 📬 API

#283 Feature/#282 팀 랭킹 api 에러 처리
  src/containers/main/TeamRankSlider/index.tsx
Labels: 📬 API, :art: 디자인

#279 Feature/#249 스터디 crud api 연결
  src/app/api/study.ts
  src/app/team/[teamId]/page.tsx
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/containers/study/Modal/DeleteStudyModal/index.tsx
  src/containers/study/Modal/StudyModal/index.tsx
  src/containers/study/Modal/StudyModal/types.ts
  src/containers/study/Modal/TerminateStudyModal/index.tsx
  src/containers/study/Modal/types.ts
  src/types.ts
Labels: 📬 API

#286 Feature/#273 커리큘럼 CRUD 토큰 연결
  src/app/api/study.ts
  src/containers/study/CurriculumCard/CurriculumItem/index.tsx
  src/containers/study/CurriculumCard/index.tsx
  src/containers/study/CurriculumModal/index.tsx
Labels: 🔨 리팩토링

#285 Feature/#284 participant menu
  src/components/ParticipantMenu/ParticipantItem/index.tsx
  src/components/ParticipantMenu/index.tsx
  src/components/ParticipantMenu/types.ts
Labels: ✨ 기능 개발

#281 Feature/#280 스터디 목록 조회 api 연결
  src/app/api/study.ts
  src/app/team/[teamId]/page.tsx
  src/components/StudyCard/index.tsx
  src/components/StudyCard/types.ts
  src/containers/team/StudyGridView/index.tsx
  src/mocks/studyCard.ts
  src/types.ts
Labels: 📬 API

#289 Feature/#288 스터디 목록 조회 작물 이미지 추가
  src/app/team/[teamId]/page.tsx
  src/components/StudyCard/index.tsx
  src/constants/crop.ts
Labels: ✨ 기능 개발

#290 Feature/#287 팀원 관련 api 연결
  src/app/api/team.ts
  src/app/team/[teamId]/page.tsx
  src/components/ParticipantMenu/ParticipantItem/index.tsx
  src/components/ParticipantMenu/index.tsx
  src/components/ParticipantMenu/types.ts
  src/containers/team/teamMember/FiredMemberModal/index.tsx
  src/containers/team/teamMember/MandateMemberModal/index.tsx
  src/containers/team/teamMember/MandateTeamLeaderModal/index.tsx
  src/containers/team/teamMember/RemoveTeamMemberModal/index.tsx
  src/containers/team/teamMember/index.tsx
  src/containers/team/teamMember/types.ts
  src/mocks/teamMember.ts
  src/types.ts
Labels: 📬 API
