Repository BDD-CLUB/01-doo-re-front, pull requests merged in 2024-09, with the labels that each got.

#303 Feature/#294 qa 반영
  src/app/api/fetcher.ts
  src/app/api/team.ts
  src/app/team/[teamId]/page.tsx
  src/app/team/[teamId]/study-gallery/page.tsx
  src/atom.ts
  src/components/StudyCard/index.tsx
  src/containers/study-gallery/StudyGallery/index.tsx
  src/containers/team/NavigationButton/index.tsx
  src/containers/team/NavigationButton/types.ts
  src/containers/team/StudyGridView/index.tsx
  src/containers/team/StudyGridView/types.ts
  src/containers/team/SuggestionCreate/index.tsx
  src/containers/team/TeamModal/index.tsx
  src/hooks/useRefetchTeamInfo.ts
  src/mocks/studyCard.ts
  src/types.ts
Labels: ✨ 기능 개발

#316 Feature/#302 커리큘럼 관련 api 수정
  src/app/api/study.ts
  src/app/team/[teamId]/page.tsx
  src/containers/study/CurriculumCard/CurriculumItem/index.tsx
  src/containers/study/CurriculumModal/index.tsx
  src/types.ts
Labels: ✨ 기능 개발

#319 Feature/#315 스터디원 목록 api 연결
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/containers/study/Participant/index.tsx
Labels: 📬 API

#306 Feature/#304 팀페이지 권한 수정
  src/app/team/[teamId]/page.tsx
  src/atom.ts
  src/components/Sidebar/SidebarContent/index.tsx
Labels: :lady_beetle: 버그, :art: 디자인

#311 Feature/#310 사이드바 현재 보고 있지 않은 팀 이름이 주황색으로 표시되는 버그 수정
  src/components/Sidebar/Category/index.tsx
Labels: :lady_beetle: 버그

#326 Feature/#325 로그아웃시 메인페이지로 이동
  src/components/Sidebar/SidebarContent/index.tsx
Labels: ✨ 기능 개발

#322 Feature/#321 스터디 종료 후 스터디 상태 변경 버튼이 안 보이도록 수정
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/containers/study/StudyInfoCard/index.tsx
  src/containers/study/StudyInfoCard/types.ts
Labels: :lady_beetle: 버그

#329 스터디 수정 시 화면 업데이트 되도록 수정
  src/app/team/[teamId]/study/[studyId]/page.tsx
Labels: :lady_beetle: 버그

#327 Feature/#323 팀 프로필 이미지 수정 시 바로 반영 안 되는 버그 수정
  src/containers/team/TeamModal/index.tsx
Labels: :lady_beetle: 버그

#330 Feature/#324 팀생성 error handling
  src/containers/team/TeamModal/index.tsx
Labels: :lady_beetle: 버그
