Repository BDD-CLUB/01-doo-re-front, pull requests merged in 2024-02, with the labels that each got.

#14 chore: eslint import plugin 자동 정렬(수정) 되도록 설정
  .vscode/settings.json
Labels: ⚙ 세팅

#15 Feature/#4 개발 서버 배포용 git action
  .github/workflows/s3-develop-deploy.yml
Labels: ✨ 기능 개발

#20 fix: 배포용 쉘 스크립트 경로 변경
  .github/workflows/s3-develop-deploy.yml
Labels: :lady_beetle: 버그

#22 chore: react icon 설치
  package-lock.json
  package.json
Labels: ⚙ 세팅

#26 chore: 커스텀 색상 추가
  src/theme/foundations/colors.ts
Labels: ⚙ 세팅, :art: 디자인

#30 chore : lf 수정
  .eslintrc.json
Labels: ⚙ 세팅

#38 Feature/#37 아이콘 버튼 테마 설정
  src/theme/components/button.ts
  src/theme/components/index.ts
Labels: :art: 디자인, 😇 P1

#40 Feature/#36 프로필 테마 설정
  package-lock.json
  package.json
  src/theme/components/avatar.ts
  src/theme/components/index.ts
Labels: :art: 디자인, 😇 P1

#39 Feature/#35 3D 잔디 props 변경
  src/components/Garden3D/Bar/index.tsx
  src/components/Garden3D/Bar/style.css
  src/components/Garden3D/Floor/index.tsx
  src/components/Garden3D/Floor/style.css
  src/components/Garden3D/index.tsx
  src/components/Garden3D/style.css
  src/components/Garden3D/types.ts
  src/mocks/Garden3D.ts
Labels: ✨ 기능 개발, 😇 P1

#43 Feature/#6 로그인페이지 UI
  next.config.js
  public/images/crops/carrot.png
  public/images/crops/pea.png
  public/images/crops/rice.png
  public/images/crops/sweet_potato.png
  public/images/crops/tomato.png
  public/images/google_sign_in.png
  src/app/page.tsx
  src/containers/main/CropLine/index.tsx
  src/containers/main/CropLine/style.css
  src/containers/main/CropLine/types.ts
  src/containers/main/GoogleLoginButton/index.tsx
  src/containers/main/MainSection/index.tsx
  src/containers/main/MainSection/types.ts
  src/containers/main/ScrollDownButton/index.tsx
  src/containers/main/ScrollDownButton/types.ts
Labels: :art: 디자인, ✨ 기능 개발

#45 Feature/#44 window 관련 에러 수정
  src/containers/main/CropLine/index.tsx
Labels: :lady_beetle: 버그

#47 feat: 텃밭에 각도 관련 props 추가
  src/components/Garden3D/index.tsx
  src/components/Garden3D/types.ts
Labels: ✨ 기능 개발

#48 Feature/#32 팀 카드 구현
  src/containers/main/TeamCard/index.tsx
  src/containers/main/TeamCard/style.css
  src/containers/main/TeamCard/types.ts
Labels: :art: 디자인, ✨ 기능 개발

#42 Feature/#18 사이드바 구현
  src/app/layout.tsx
  src/components/Sidebar/Button/CategoryButton/index.tsx
  src/components/Sidebar/Button/SidebarIconButton/index.tsx
  src/components/Sidebar/Category/index.tsx
  src/components/Sidebar/index.tsx
  src/components/Sidebar/type.ts
  src/mocks/sidebar.ts
  src/theme/index.ts
Labels: :art: 디자인, ✨ 기능 개발

#51 Feature/#49 팀 랭킹 구현
  src/app/page.tsx
  src/containers/main/TeamRankBG/index.tsx
  src/containers/main/TeamRankDescription/index.tsx
  src/containers/main/TeamRankSlider/index.tsx
  src/mocks/Garden3D.ts
  src/mocks/TeamRanking.ts
  src/types.ts
Labels: :art: 디자인, ✨ 기능 개발

#53 Feature/#52 레이아웃 밀리는 현상 수정
  src/app/layout.tsx
Labels: :art: 디자인

#54 Feature/#50 색상 상수 추가
  src/constants/color.ts
  src/theme/foundations/colors.ts
Labels: :art: 디자인

#58 Feature/#56 레이아웃 수정
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Sidebar/index.tsx
  src/containers/main/TeamRankDescription/index.tsx
  src/containers/main/TeamRankSlider/index.tsx
Labels: :art: 디자인, 😇 P1

#66 Feature/#64 gray 컬러 커스텀
  src/theme/foundations/colors.ts
Labels: :art: 디자인

#68 Feature/#67 gray50컬러 추가
  src/app/team/[teamId]/page.tsx
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/theme/foundations/colors.ts
Labels: :art: 디자인

#57 Feature/#55 crop line 겹치는 현상
  src/containers/main/CropLine/index.tsx
  src/containers/main/CropLine/style.css
Labels: :lady_beetle: 버그

#73 Feature/#72 Cropline 안 움직이는 현상
  src/containers/main/CropLine/style.css
Labels: :lady_beetle: 버그

#69 Feature/#60 팀 스터디 레이아웃 구현
  src/app/team/[teamId]/page.tsx
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/components/Sidebar/index.tsx
Labels: :art: 디자인, 😇 P1

#80 Feature/#70 콘텐츠 넓이 고정
  src/app/team/[teamId]/layout.tsx
  src/app/team/[teamId]/page.tsx
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/components/Sidebar/index.tsx
  src/constants/size.ts
Labels: :art: 디자인, 😇 P1

#34 Feature/#33 스터디페이지 참여인원 구현
  src/containers/study/Participant/index.tsx
  src/containers/study/Participant/style.css
  src/containers/study/Participant/types.ts
  src/mocks/participant.ts
  src/types.ts
Labels: :art: 디자인, ✨ 기능 개발

#85 Feature/#62 resize textarea 구현
  package-lock.json
  package.json
  src/components/AutoResizeTextarea/index.tsx
  src/components/AutoResizeTextarea/type.ts
Labels: ✨ 기능 개발, 😇 P1

#24 Feature/#7 학습카드 구현
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/components/StudyAssetCard/index.tsx
  src/components/StudyAssetCard/types.ts
  src/mocks/study.ts
Labels: :art: 디자인, ✨ 기능 개발

#25 Feature/#8 스터디카드 구현
  .vscode/settings.json
  public/png/circle.png
  src/app/team/[teamId]/page.tsx
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/components/StudyCard/index.tsx
  src/components/StudyCard/types.ts
  src/mocks/studyAssetCard.ts
  src/mocks/studyCard.ts
Labels: :art: 디자인, ✨ 기능 개발

#89 Feature/#79 탭 버튼 구현
  src/app/team/[teamId]/page.tsx
  src/components/TabButton/index.tsx
  src/components/TabButton/type.ts
  src/mocks/team.ts
  src/types.ts
Labels: :art: 디자인, ✨ 기능 개발

#91 Feature/#90 팀 카드 애니메이션 구현
  src/containers/main/TeamRankSlider/index.tsx
Labels: ✨ 기능 개발

#84 Feature/#71 팀 출석률 구현
  src/containers/team/AttendanceRate/index.tsx
  src/containers/team/AttendanceRate/types.ts
Labels: :art: 디자인, ✨ 기능 개발

#88 Feature/#86 gardend3D 컴포넌트 크기 확대
  src/components/Garden3D/index.tsx
  src/components/Garden3D/style.css
  src/components/Garden3D/types.ts
  src/containers/main/TeamCard/index.tsx
Labels: :art: 디자인, ✨ 기능 개발

#96 Feature/#81 커리큘럼 구현
  public/images/curriculumCrops/carrot_5.png
  src/components/CurriculumCard/CurriculumItem/index.tsx
  src/components/CurriculumCard/index.tsx
  src/components/CurriculumCard/types.ts
  src/mocks/curriculum.ts
Labels: :art: 디자인, ✨ 기능 개발

#97 Feature/#7 학습카드 구현
  src/app/team/[teamId]/page.tsx
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/components/StudyAssetCard/index.tsx
Labels: :art: 디자인

#95 Feature/#76 스터디 정보 카드
  src/containers/study/StudyInfoCard/StudyProgress/index.tsx
  src/containers/study/StudyInfoCard/index.tsx
  src/containers/study/StudyInfoCard/types.ts
  src/utils/dateFormat.ts
Labels: ✨ 기능 개발

#99 Feature/#98 피드 구현
  src/containers/study/Feed/index.tsx
  src/containers/study/Feed/type.ts
  src/mocks/feed.ts
Labels: :art: 디자인, ✨ 기능 개발

#101 Feature/#27 팀페이지 팀원 목록 구현
  src/components/StudyAssetCard/index.tsx
  src/containers/team/teamMember/index.tsx
  src/containers/team/teamMember/types.ts
  src/mocks/teamMember.ts
  src/theme/components/avatar.ts
Labels: :art: 디자인

#102 Feature/#100 스터디 페이지 레이아웃
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/components/CurriculumCard/index.tsx
  src/components/StudyCard/types.ts
  src/components/Title/index.tsx
  src/containers/study/Feed/index.tsx
  src/containers/study/Participant/index.tsx
  src/containers/study/StudyInfoCard/index.tsx
  src/mocks/studyCard.ts
  src/style.css
Labels: :art: 디자인

#105 Feature/#103 팀 페이지 레이아웃 배치
  src/app/team/[teamId]/page.tsx
  src/components/Title/index.tsx
Labels: :art: 디자인

#107 Feature/#106 study card props 오류
  src/app/team/[teamId]/page.tsx
  src/components/StudyCard/types.ts
  src/mocks/studyCard.ts
  src/mocks/teamMember.ts
Labels: :lady_beetle: 버그

#111 Feature/#109 반응형 폰트 스타일 지정
  src/theme/foundations/index.ts
  src/theme/foundations/textStyles.ts
Labels: ⚙ 세팅, :art: 디자인
