Repository BDD-CLUB/01-doo-re-front, pull requests merged in 2024-05, with the labels that each got.

#215 Feature/#214 스터디 자료 전체보기
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/theme/components/button.ts
Labels: ✨ 기능 개발

#189 Feature/#180 학습자료 상세 모달
  src/components/StudyAssetCard/index.tsx
  src/containers/study/StudyAssetModal/index.tsx
  src/containers/study/StudyAssetModal/types.ts
  src/mocks/studyAssetFileData.ts
  src/mocks/studyAssetImgData.ts
  src/mocks/studyAssetLinkData.ts
Labels: :art: 디자인, ✨ 기능 개발

#202 Feature/#201 스터디 종료 삭제 버튼 구현
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/containers/study/Modal/DeleteStudyModal/index.tsx
  src/containers/study/Modal/TerminateStudyModal/index.tsx
  src/containers/study/Modal/types.ts
  src/containers/study/StudyControlPanel/index.tsx
  src/containers/study/StudyControlPanel/types.ts
Labels: :art: 디자인, ✨ 기능 개발

#199 Feature/#186 팀 생성 모달 구현
  src/components/IconBox/index.tsx
  src/components/Sidebar/CreateTeamModal/index.tsx
  src/components/Sidebar/SidebarContent/index.tsx
  src/components/Sidebar/type.ts
Labels: :art: 디자인, ✨ 기능 개발

#212 Feature/#187 학습자료 생성모달
  src/components/IconBox/index.tsx
  src/containers/study/DocumentModal/index.tsx
  src/containers/study/DocumentModal/type.ts
Labels: ✨ 기능 개발

#209 Feature/#205 DatePicker 구현
  package-lock.json
  package.json
  src/components/StyledDatePicker/index.tsx
  src/components/StyledDatePicker/style.css
  src/components/StyledDatePicker/types.ts
  src/theme/components/input.ts
Labels: :art: 디자인, ✨ 기능 개발

#216 Feature/#198 학습자료 갤러리
  src/app/team/[teamId]/study/[studyId]/asset/page.tsx
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/containers/studyAsset/StudyAssets/index.tsx
  src/mocks/studyAssetCardAll.ts
Labels: :art: 디자인, ✨ 기능 개발

#208 Feature/#82 커리큘럼 편집 모달창 구현
  package-lock.json
  package.json
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/components/CurriculumCard/index.tsx
  src/containers/study/CurriculumCard/CurriculumItem/index.tsx
  src/containers/study/CurriculumCard/index.tsx
  src/containers/study/CurriculumCard/types.ts
  src/containers/study/CurriculumModal/index.tsx
Labels: ✨ 기능 개발

#211 Feature/#204 스터디 생성 모달 구현
  package-lock.json
  package.json
  src/components/Selector/index.tsx
  src/components/Selector/types.ts
  src/constants/crop.ts
  src/containers/team/CreateStudyModal/index.tsx
  src/containers/team/CreateStudyModal/types.ts
Labels: :art: 디자인, ✨ 기능 개발

#219 Feature/#200 스터디 네비게이션 구현
  src/app/team/[teamId]/page.tsx
  src/components/StudyAssetCard/types.ts
  src/components/TabButton/index.tsx
  src/constants/team.ts
  src/containers/study/StudyAssetModal/index.tsx
  src/containers/team/AssetGridView/index.tsx
  src/containers/team/AssetGridView/types.ts
  src/containers/team/NavigationButton/index.tsx
  src/containers/team/NavigationButton/types.ts
  src/containers/team/StudyGridView/index.tsx
  src/containers/team/StudyGridView/types.ts
  src/mocks/studyAssetCard.ts
  src/mocks/studyCard.ts
  src/mocks/team.ts
  src/theme/components/button.ts
  src/theme/foundations/colors.ts
  src/types.ts
Labels: :art: 디자인, ✨ 기능 개발

#230 Fix/#229 배포 빌드 버그 픽스
  package-lock.json
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/containers/studyAsset/StudyAssets/index.tsx
  src/containers/team/CreateStudyModal/index.tsx
  src/mocks/curriculum.ts
  src/mocks/studyAssetCardAll.ts
Labels: :lady_beetle: 버그

#222 Feature/#222 pageNavigator 생성
  src/app/api/study.ts
  src/components/PageNavigator/index.tsx
  src/components/PageNavigator/types.ts
  src/containers/studyAsset/StudyAssets/index.tsx
Labels: ✨ 기능 개발

#223 Feature/#220 커리큘럼 CRUD API 연결
  src/app/api/study.ts
  src/containers/study/CurriculumCard/CurriculumItem/index.tsx
  src/containers/study/CurriculumCard/index.tsx
  src/containers/study/CurriculumCard/types.ts
  src/containers/study/CurriculumModal/index.tsx
  src/containers/study/CurriculumModal/type.ts
  src/types.ts
Labels: 📬 API

#233 Featrue/#231 study api feat 이름변경
  src/app/api/study.ts
Labels: 📬 API

#234 fix: 타입 안맞는 에러 픽스
  src/app/api/curriculumItem.ts
  src/mocks/curriculum.ts
Labels: :lady_beetle: 버그
