Repository BDD-CLUB/01-doo-re-front, pull requests merged in 2024-06, with the labels that each got.

#244 Feature/#238 팀 생성
  src/app/api/fetcher.ts
  src/app/api/team.ts
  src/components/Sidebar/SidebarContent/index.tsx
  src/containers/team/TeamModal/index.tsx
  src/containers/team/TeamModal/type.ts
Labels: 📬 API, ✨ 기능 개발

#245 [FEAT] 머지하기 전, build 테스트 기능
  .github/workflows/develop-buildtest.yml
Labels: ✨ 기능 개발

#246 Feature/#235 스터디 수정 모달 구현
  src/app/team/[teamId]/page.tsx
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/containers/study/Modal/StudyModal/index.tsx
  src/containers/study/Modal/StudyModal/types.ts
  src/containers/team/CreateStudyModal/types.ts
Labels: :art: 디자인, ✨ 기능 개발

#250 Feature/#242 로그인 버그 픽스
  src/app/api/login.ts
  src/app/oauth2/code/google/page.tsx
Labels: :lady_beetle: 버그

#252 Feature/#228 팀페이지, 스터디 페이지 학습자료 crud
  src/app/api/document.ts
  src/types.ts
Labels: 📬 API

#255 [FEAT] StudyAsset -> Document 용어통일 #254
  src/app/team/[teamId]/page.tsx
  src/app/team/[teamId]/study/[studyId]/document/page.tsx
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/components/DocumentCard/index.tsx
  src/components/DocumentCard/types.ts
  src/containers/document/Documents/index.tsx
  src/containers/study/CreateDocumentModal/index.tsx
  src/containers/study/CreateDocumentModal/type.ts
  src/containers/study/DocumentModal/index.tsx
  src/containers/study/DocumentModal/types.ts
  src/containers/study/StudyAssetModal/index.tsx
  src/containers/team/AssetGridView/index.tsx
  src/containers/team/AssetGridView/types.ts
  src/containers/team/DocumentGridView/index.tsx
  src/containers/team/DocumentGridView/types.ts
  src/mocks/documentCard.ts
  src/mocks/documentCardAll.ts
  src/mocks/documentFileData.ts
  src/mocks/documentImgData.ts
  src/mocks/documentLinkData.ts
Labels: 🔨 리팩토링

#257 Feature/#240 자신이 속한 팀 조회
  src/app/api/team.ts
  src/components/Sidebar/SidebarContent/index.tsx
  src/components/Sidebar/type.ts
  src/containers/main/GoogleLoginButton/index.tsx
  src/hooks/useFetchWithToken.ts
  src/hooks/useGetUser.ts
  src/mocks/sidebar.ts
Labels: ✨ 기능 개발

#259 Feature/#258 커리큘럼 api 백엔드 수정 및 권한 처리
  src/app/api/study.ts
  src/containers/study/CurriculumCard/CurriculumItem/index.tsx
  src/containers/study/CurriculumCard/index.tsx
  src/types.ts
Labels: ✨ 기능 개발

#261 refactor : 사용안하는 accessType 제거 및 import 순서 변경
  src/containers/study/CurriculumCard/index.tsx
Labels: :lady_beetle: 버그

#264 Feature/#239 초대코드 기능
  src/app/api/fetcher.ts
  src/app/api/team.ts
  src/app/oauth2/code/google/page.tsx
  src/app/team/[teamId]/join/page.tsx
  src/app/team/[teamId]/page.tsx
  src/atom.ts
  src/constants/googleLoginUrl.ts
  src/containers/main/GoogleLoginButton/index.tsx
  src/hooks/useFetchWithToken.ts
Labels: ✨ 기능 개발

#270 Feature/#268 사이드바api
  src/app/api/member.ts
  src/app/api/team.ts
  src/components/Sidebar/SidebarContent/index.tsx
Labels: :lady_beetle: 버그, ✨ 기능 개발

#269 feat : 토큰 사용해서 팀 생성 api 연결
  src/app/api/fetcher.ts
  src/app/api/team.ts
  src/containers/team/TeamModal/index.tsx
Labels: 📬 API
