Repository BDD-CLUB/01-doo-re-front, pull requests merged in 2024-04, with the labels that each got.

#178 Feature/#177 radio component
  src/components/StyledRadio/index.tsx
  src/components/StyledRadio/types.ts
  src/components/StyledRadioGroup/index.tsx
  src/components/StyledRadioGroup/types.ts
Labels: ✨ 기능 개발

#185 Feature/#184 첨부 파일 관련 공통 컴포넌트 구현
  src/components/IconBox/index.tsx
  src/components/IconBox/type.ts
  src/theme/components/button.ts
Labels: :art: 디자인, ✨ 기능 개발

#179 Feature/#153 학습자료 카드 반응형 구현
  src/components/StudyAssetCard/index.tsx
Labels: :art: 디자인

#183 Feature/#181 Selector 구현
  src/components/Selector/index.tsx
  src/components/Selector/types.ts
Labels: :art: 디자인, ✨ 기능 개발

#191 Feature/#190 첨부 파일 관련 공통 컴포넌트 수정
  src/components/IconBox/index.tsx
Labels: :art: 디자인

#194 Feature/#192 모달 컴포넌트 size props 추가
  src/components/Modal/ActionModal/index.tsx
  src/components/Modal/AlertModal/index.tsx
  src/components/Modal/ConfirmModal/index.tsx
  src/components/Modal/types.ts
Labels: :art: 디자인

#197 Feature/#196 auto resize textarea 아이콘 추가기능 확장
  src/components/AutoResizeTextarea/index.tsx
  src/components/AutoResizeTextarea/type.ts
  src/components/IconBox/index.tsx
  src/theme/components/input.ts
  src/theme/components/textarea.ts
Labels: :art: 디자인, ✨ 기능 개발

#207 Feature/#206 Selector borderRadius 수정
  src/components/Selector/index.tsx
Labels: :art: 디자인
