Repository BDD-CLUB/01-doo-re-front, pull requests merged in 2024-11, with the labels that each got.

#337 Feature/#336 팀페이지에서 사용자 별 보이는 컴포넌트 제한
  src/app/team/[teamId]/page.tsx
  src/constants/team.ts
Labels: ✨ 기능 개발

#338 Feature/#333 스터디 페이지 접속 시 오류가 뜨는 현상
  src/containers/study/Participant/index.tsx
Labels: :lady_beetle: 버그

#335 Feature/#334 커리큘럼 api 호출 후 동작 수정
  src/app/api/study.ts
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/atom.ts
  src/containers/study/CurriculumCard/CurriculumItem/index.tsx
  src/containers/study/CurriculumCard/index.tsx
  src/containers/study/CurriculumModal/index.tsx
  src/hooks/useRefetchCurriculum.ts
  src/types.ts
Labels: ✨ 기능 개발

#345 Feature/#343 사이드바 로그인버튼
  src/components/Sidebar/SidebarContent/index.tsx
  src/containers/main/GoogleLoginButton/index.tsx
Labels: :lady_beetle: 버그

#344 Feature/#332 rerendering 문제
  src/app/team/[teamId]/document/page.tsx
  src/app/team/[teamId]/page.tsx
  src/app/team/[teamId]/study-gallery/page.tsx
  src/app/team/[teamId]/study/[studyId]/document/page.tsx
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/containers/document/Documents/index.tsx
  src/containers/document/Documents/types.ts
  src/containers/study-gallery/StudyGallery/index.tsx
  src/containers/study/CreateDocumentModal/index.tsx
  src/containers/study/Modal/DeleteStudyModal/index.tsx
  src/containers/study/Modal/StudyModal/index.tsx
  src/containers/study/Modal/types.ts
Labels: :lady_beetle: 버그

#342 Feature/#341 스터디 카드에서 종료된 스터디와 진행중인 스터디 구분 표시
  src/components/StudyCard/index.tsx
Labels: ✨ 기능 개발

#309 Feature/#308 팀페이지 설명글 반응형 수정
  src/components/Title/index.tsx
Labels: :lady_beetle: 버그

#347 Feature/#346 스터디페이지에서 학습자료 세션 수정
  src/app/team/[teamId]/study/[studyId]/page.tsx
Labels: :art: 디자인

#356 Feature/#354 QA에서 발견된 UX 문제 해결
  src/app/team/[teamId]/page.tsx
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/containers/study/CreateDocumentModal/index.tsx
Labels: ✨ 기능 개발

#352 Feature/#349 첨부된 학습자료 클릭 시 새탭으로 띄워지도록 수정
  src/containers/study/DocumentModal/index.tsx
Labels: ✨ 기능 개발

#353 Feature/#350 파일 여러 개 등록 시 썸네일 이미지 에러 수정
  src/components/DocumentCard/index.tsx
Labels: :lady_beetle: 버그

#351 Feature/#348 학습자료 수정 시 모달의 제목을 학습자료 수정으로 변경
  src/containers/study/CreateDocumentModal/index.tsx
Labels: :art: 디자인

#357 Feature/#355 re rerendering
  src/app/team/[teamId]/page.tsx
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/containers/study/DocumentModal/index.tsx
  src/containers/study/StudyParticipantMenu/index.tsx
  src/containers/study/StudyParticipantMenu/types.ts
  src/containers/team/DocumentGridView/index.tsx
  src/containers/team/DocumentGridView/types.ts
  src/containers/team/teamMember/MandateTeamLeaderModal/index.tsx
  src/containers/team/teamMember/RemoveTeamMemberModal/index.tsx
  src/containers/team/teamMember/index.tsx
  src/hooks/useFetchWithToken.ts
Labels: :lady_beetle: 버그
