Repository BDD-CLUB/01-doo-re-front, pull requests merged in 2024-03, with the labels that each got.

#113 Feature/#112 반응형 버튼 크기 지정
  src/theme/components/button.ts
Labels: ⚙ 세팅, :art: 디자인

#115 Feature/#114 반응형 크기 지정
  src/theme/components/avatar.ts
  src/theme/components/button.ts
  src/theme/foundations/textStyles.ts
Labels: ⚙ 세팅, :art: 디자인

#120 feat : fetcher 함수 구현
  src/app/api/fetcher.ts
Labels: ✨ 기능 개발

#116 Feature/#110 사이드바 반응형 수정
  src/app/layout.tsx
  src/app/team/[teamId]/layout.tsx
  src/components/Sidebar/Button/CategoryButton/index.tsx
  src/components/Sidebar/Category/index.tsx
  src/components/Sidebar/SidebarContent/index.tsx
  src/components/Sidebar/index.tsx
  src/components/Sidebar/type.ts
Labels: :art: 디자인

#121 Feature/#119-Study_Api_코드
  src/app/api/study.ts
  src/types.ts
Labels: ✨ 기능 개발

#122 Feature/#117 팀 랭킹 페이지 반응형 레이아웃
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/containers/main/MainSection/index.tsx
  src/containers/main/TeamRankDescription/index.tsx
  src/containers/main/TeamRankSlider/index.tsx
  src/mocks/TeamRanking.ts
  src/theme/foundations/textStyles.ts
  src/types.ts
Labels: :art: 디자인, ✨ 기능 개발

#125 Feature/#124 메인페이지 반응형 레이아웃
  src/app/layout.tsx
  src/app/page.tsx
  src/containers/main/CropLine/index.tsx
  src/containers/main/GoogleLoginButton/index.tsx
  src/theme/foundations/textStyles.ts
Labels: :art: 디자인

#128 Feature/#126 팀페이지 반응형 구현
  src/app/team/[teamId]/layout.tsx
  src/app/team/[teamId]/page.tsx
  src/components/StudyCard/index.tsx
  src/components/Title/index.tsx
  src/containers/team/AttendanceRate/index.tsx
  src/containers/team/teamMember/index.tsx
Labels: :art: 디자인

#138 Feature/#132 반응형 폰트 스타일 수정
  src/theme/breakpoints.ts
  src/theme/foundations/textStyles.ts
  src/theme/index.ts
Labels: :art: 디자인

#129 Feature/#127 스터디페이지 반응형 구현
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/components/CurriculumCard/index.tsx
  src/components/StudyAssetCard/index.tsx
  src/containers/study/StudyInfoCard/StudyProgress/index.tsx
  src/containers/study/StudyInfoCard/index.tsx
Labels: :art: 디자인

#137 Feature/#136 fetcher body FormData 추가
  src/app/api/fetcher.ts
Labels: ✨ 기능 개발

#134 Feature/#131 Team Api 코드
  src/app/api/team.ts
  src/types.ts
Labels: ✨ 기능 개발

#149 Feature/#147 커리큘럼 반응형 구현
  src/components/CurriculumCard/CurriculumItem/index.tsx
Labels: :art: 디자인

#150 Feature/#148 피드 반응형 구현
  src/containers/study/Feed/index.tsx
Labels: :art: 디자인

#155 Feature/#151 버튼 테마 추가
  src/theme/components/button.ts
Labels: :art: 디자인

#160 Feature/#159 화면 크기 상수로 지정
  src/components/Sidebar/index.tsx
  src/constants/size.ts
  src/theme/breakpoints.ts
Labels: :art: 디자인

#158 Feature/#157 팀&스터디 여백 삭제
  src/app/layout.tsx
Labels: :art: 디자인

#143 Feature/#142 팀페이지에서 텃밭 렌더링
  src/app/team/[teamId]/page.tsx
Labels: :art: 디자인

#156 Feature/#146 모달 공통 컴포넌트 구현
  src/components/Modal/ActionModal/index.tsx
  src/components/Modal/AlertModal/index.tsx
  src/components/Modal/ConfirmModal/index.tsx
  src/components/Modal/types.ts
Labels: :art: 디자인

#161 Feature/#144 출석률 반응형 구현
  src/containers/team/AttendanceRate/index.tsx
Labels: :art: 디자인

#165 Feature/#164 반응형 폰트 스타일 추가
  src/theme/foundations/textStyles.ts
Labels: :art: 디자인

#167 refactor: 사용되지 않는 className id로 대체
  src/containers/main/TeamCard/index.tsx
Labels: 🔨 리팩토링

#163 Feature/#133-사이드바에서_스크롤바_생성
  src/app/layout.tsx
  src/components/CurriculumCard/index.tsx
  src/components/Sidebar/SidebarContent/index.tsx
  src/containers/main/MainSection/index.tsx
  src/containers/study/Feed/index.tsx
  src/containers/study/Participant/index.tsx
  src/mocks/sidebar.ts
  src/style.css
Labels: :art: 디자인, ✨ 기능 개발

#135 Feature/#130 curriculum api 수정
  src/app/api/curriculumItem.ts
  src/types.ts
Labels: 📬 API, ✨ 기능 개발

#172 Feature/#171 레이아웃 높이 짤리는 부분 수정
  src/app/layout.tsx
  src/app/page.tsx
Labels: :art: 디자인

#173 Feature/#169 스터디 진행률 반응형 적용
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/containers/study/StudyInfoCard/index.tsx
Labels: :art: 디자인

#174 Feature/#168 팀 소개글 반응형 적용
  public/images/doore_logo.png
  src/components/Title/index.tsx
Labels: :art: 디자인

#170 Feature/#145 스터디페이지 참여인원 반응형 구현
  src/containers/study/Participant/index.tsx
  src/mocks/participant.ts
Labels: :art: 디자인

#176 Feature/#175 인풋 필드 테마 적용
  src/theme/components/index.ts
  src/theme/components/input.ts
  src/theme/components/textarea.ts
Labels: :art: 디자인
