Repository BDD-CLUB/01-doo-re-front, pull requests merged in 2025-02, with the labels that each got.

#389 Feature/#388 스터디페이지에서 스터디원이 아닌 팀원에게 학습자료 생성 버튼이 안 보이도록 수정
  src/app/team/[teamId]/study/[studyId]/page.tsx
Labels: :art: 디자인

#393 Feature/#392 스터디페이지 학습자료 공개 범위 옵션 제거
  src/app/team/[teamId]/document/page.tsx
  src/app/team/[teamId]/page.tsx
  src/components/DocumentCard/index.tsx
  src/containers/document/Documents/index.tsx
  src/containers/study/CreateDocumentModal/index.tsx
  src/containers/study/CreateDocumentModal/type.ts
  src/containers/study/DocumentModal/index.tsx
  src/containers/study/DocumentModal/types.ts
  src/containers/team/DocumentGridView/index.tsx
  src/types.ts
Labels: :art: 디자인

#391 Feature/#390 스터디페이지 팀장에게 스터디장 삭제 표시
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/components/ParticipantMenu/ParticipantItem/index.tsx
  src/components/ParticipantMenu/index.tsx
  src/components/ParticipantMenu/types.ts
  src/containers/study/StudyParticipantMenu/index.tsx
  src/containers/study/StudyParticipantMenu/types.ts
  src/containers/team/teamMember/index.tsx
Labels: ✨ 기능 개발

#395 Feature/#394 종료 날짜 지정 안 했을 시 스터디페이지에서 종료 날짜 안 보이게 수정
  src/app/team/[teamId]/study/[studyId]/page.tsx
  src/containers/study/StudyInfoCard/index.tsx
  src/containers/study/StudyInfoCard/types.ts
Labels: :art: 디자인

#398 Feature/#396 스터디라는 단어만 다른 색상으로 표시되도록 구현
  src/components/Sidebar/Button/CategoryButton/index.tsx
  src/components/Sidebar/Category/index.tsx
  src/components/Sidebar/type.ts
  src/components/StudyCard/index.tsx
Labels: :art: 디자인

#399 Feature/#397 학습자료 상세 조회 시 파일 경로가 아닌 파일명으로 표시
  src/containers/study/DocumentModal/index.tsx
  src/mocks/documentCard.ts
  src/mocks/documentCardAll.ts
  src/types.ts
Labels: :art: 디자인

#401 Feature/#400 학습자료 URL 프로토콜이 없는 경우 절대 경로로 변환
  src/containers/study/DocumentModal/index.tsx
Labels: ✨ 기능 개발

#403 Feature/#402 팀 및 스터디명이 긴 경우 소개글과 다른 컴포넌트가 겹치는 현상 수정
  src/components/Title/index.tsx
Labels: :lady_beetle: 버그
